### ISSUE TITLE
Installing from git

### ISSUE THREAD

**Issue by bashu** [APSL/puput#12]
```python
Exception:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/util.py", line 627, in unpack_file
    and is_svn_page(file_contents(filename))):
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/pip/util.py", line 210, in file_contents
    return fp.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by bashu** [comment]
nevermind, forgot to add git+http...
