### ISSUE TITLE
ImportError: No module named puput after 0.9 upgrade

### ISSUE THREAD

**Issue by nicklo** [APSL/puput#127]
I'm getting the error "ImportError: No module named puput" after a pip upgrade from 0.8 to 0.9 on a fresh virtualenv for an existing project. This is with Django==1.10.7, wagtail==1.9, django-compressor==2.1.1 and django-el-pagination==3.1.0 on Python2.7 on MacOS 10.12.

(Note in following I'm using  --no-deps because I'm trying to keep django 1.10.7)

```
18:09:19 • nicklo • ~/Sites/clientproject
↪ pip install -U --no-deps puput
Collecting puput
Installing collected packages: puput
  Found existing installation: puput 0.8
    Uninstalling puput-0.8:
      Successfully uninstalled puput-0.8
Successfully installed puput-0.9

(clientproject)  18:09:45 • nicklo • ~/Sites/clientproject
↪ python djangoware/manage.py runserver 9000
Unhandled exception in thread started by <function wrapper at 0x10367b140>
Traceback (most recent call last):
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named puput

^C(clientproject)  18:10:37 • nicklo • ~/Sites/clientproject
↪ pip install -U --no-deps puput==0.8
Collecting puput==0.8
Installing collected packages: puput
  Found existing installation: puput 0.9
    Uninstalling puput-0.9:
      Successfully uninstalled puput-0.9
Successfully installed puput-0.8

(clientproject)  18:10:51 • nicklo • ~/Sites/clientproject
↪ pip install -U --no-deps puput==0.8
Requirement already up-to-date: puput==0.8 in /Users/nicklo/.virtualenvs/clientproject/lib/python2.7/site-packages
(clientproject)  18:10:54 • nicklo • ~/Sites/clientproject
↪ python djangoware/manage.py runserver 9000
Performing system checks...

System check identified no issues (0 silenced).
August 07, 2017 - 18:11:00
Django version 1.10.7, using settings 'nucleus.settings'
Starting development server at http://127.0.0.1:9000/
Quit the server with CONTROL-C.
```

**Comment by marctc** [comment]
Hi @nicklo. Can you try it again? Install again the 0.9 version (remove and reinstall)

**Comment by nicklo** [comment]
**Success!**

```
↪ pip install -U --no-deps puput
Collecting puput
  Downloading puput-0.9-py2-none-any.whl (359kB)
    100% |████████████████████████████████| 368kB 1.4MB/s
Installing collected packages: puput
  Found existing installation: puput 0.8
    Uninstalling puput-0.8:
      Successfully uninstalled puput-0.8
Successfully installed puput-0.9
(clientproject)  11:48:00 • nicklo • ~/Sites/clientproject
↪ python djangoware/manage.py runserver 9000
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): puput.
Run 'python manage.py migrate' to apply them.

August 08, 2017 - 11:48:07
Django version 1.10.7, using settings 'nucleus.settings'
Starting development server at http://127.0.0.1:9000/
Quit the server with CONTROL-C.

```
Thanks @marctc
