### ISSUE TITLE
puput.models.DoesNotExist: BlogPage matching query does not exist.

### ISSUE THREAD

**Issue by zugspitze** [APSL/puput#162]
Thanks a lot for providing puput package. I am trying to use it for my website. However, I have some issues in making it work.

I can access the blog_admin site but not the blog site. When I try to fix the tree in wagtail using './manage.py fixtree', I get the following error:

puput.models.DoesNotExist: BlogPage matching query does not exist.

I accidentally deleted the blog page from the blog_admin page. I was thinking that it's a normal django admin page, where you can add/delete anything. Is there a way to make it work again?
 
Could you please help me with this issue.

Best regards,
Amit

**Comment by MiltonLn** [comment]
Hey @zugspitze thanks for using Puput!

Because Puput is built on top of Wagtail's ecosystem, the blog is a page itself and you shall not delete it.(I've read through the documentation and we are not giving that warning @marctc should we improve that section in docs right?)

I've replayed your issue and it was quickly solved by running `python manage.py puput_initial_data` again to re-create the blog page, did you try that?

Hope that solves the issue.

**Comment by zugspitze** [comment]
After running `python manage.py puput_initial_data`, I get the following error:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/puput/management/commands/puput_initial_data.py", line 35, in handle
    rootpage.add_child(instance=blogpage)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/treebeard/mp_tree.py", line 1013, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/treebeard/mp_tree.py", line 389, in process
    newobj.save()
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/wagtail/core/models.py", line 441, in save
    self.full_clean()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/wagtail/core/models.py", line 431, in full_clean
    super().full_clean(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 1249, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'path': ['Page with this Path already exists.']}
```

**Comment by MiltonLn** [comment]
Are you really sure that you deleted the Blog Page? because that error in `puput_initial_data` only appears when you didn't, you can check it in django shell by running `Page.objects.get(title="Blog", slug='blog')` and it will print something like `<Page: Blog>`

**Comment by zugspitze** [comment]
It gives an error:
```
(InteractiveConsole)
>>> Page.objects.get(title="Blog", slug='blog')
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
NameError: name 'Page' is not defined
```

**Comment by MiltonLn** [comment]
You need to import `Page` model, the whole process is:

1. Activate your virtualenv
2. go to `python manage.py shell`
3. Run this code:

```python
from wagtail.core.models import Page
Page.objects.get(title='Blog', slug='blog')
```

**Comment by zugspitze** [comment]
Ahh, sorry forgot to import model. Now I get the following error:
```
>>> Page.objects.get(title='Blog', slug='blog')
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
wagtail.core.models.DoesNotExist: Page matching query does not exist.
```

**Comment by MiltonLn** [comment]
Woah, that's weird. But the important thing about the process is that you shall not delete the blog page. If you are in early development phases you can reset your db and set it up again (migrate and puput_initial_data) to have it working again. Maybe you can manually create it by reading through `puput_initial_data` command code.

Anyway you should create a Blog Page as is described in `puput_initial_data` command.

**Comment by zugspitze** [comment]
Unfortunately, it's in production. And, there are other entries in the database.

**Comment by zugspitze** [comment]
Is it possible to create a separate database for puput? So that I can keep my other database untouched.

**Comment by johnfraney** [comment]
@zugspitze You can configure multiple databases in Django and even specify that certain apps interact with a specific database. Check out the [Database routing](https://docs.djangoproject.com/en/2.0/topics/db/multi-db/#an-example) example for a quick run-down on how to set this up.

**Comment by MiltonLn** [comment]
Closing it, please reopen if this is still an issue.
