### ISSUE TITLE
arrow.gif does not exist, collectstatic fails

### ISSUE THREAD

**Issue by corpulent** [APSL/puput#164]
I am getting this error when i run `python manage.py collectstatic`.

```
Post-processing 'colorful/colorPicker.css' failed!

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 189, in handle
    collected = self.collect()
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'colorful/arrow.gif' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fd0b483f7f0>.

The CSS file 'colorful/colorPicker.css' references a file which could not be found:
  colorful/arrow.gif
```

It looks like `arrow.gif` does not exist.

**Comment by mina-gaid** [comment]
Having the same issue here. The gif was either moved/removed or the CSS is pointing in the wrong location
