### ISSUE TITLE
Support Wagtail 2.2.x

### ISSUE THREAD

**Issue by MIKNOTAURO** [APSL/puput#173]
HI guys!
Any plan/roadmap to add support for Wagtail 2.2.x?

**Comment by MIKNOTAURO** [comment]
I was getting this 
![image](https://user-images.githubusercontent.com/2102746/45300876-21a07e00-b4d5-11e8-8b67-de2ef800c28e.png)

And I just did >>>pip install wagtail==2.2.2 (to upgrade wagtail)

And after that, I got this

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f825b310950>
Traceback (most recent call last):
  File "..../EnvBlogService/lib/python3.5/site-packages/django/urls/resolvers.py", line 542, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../EnvBlogService/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File ".../EnvBlogService/lib/python3.5/site-packages/django/urls/resolvers.py", line 400, in check
    warnings.extend(check_resolver(pattern))
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File ".../EnvBlogService/lib/python3.5/site-packages/django/urls/resolvers.py", line 400, in check
    warnings.extend(check_resolver(pattern))
  File ".../EnvBlogService/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File ".../EnvBlogService/lib/python3.5/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File ".../EnvBlogService/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File ".../EnvBlogService/lib/python3.5/site-packages/django/urls/resolvers.py", line 549, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name))
django.core.exceptions.ImproperlyConfigured: The included URLconf '<module 'wagtail.search.urls' from '.../EnvBlogService/lib/python3.5/site-packages/wagtail/search/urls/__init__.py'>' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.
 
So, I have to install wagtail(2.2.2) then add puput as a plugin (pip install puput)
Then update this dependencies
html5lib-0.999999999 -> 1.0.1
Unidecode-0.4.21-> 1.0.22
draftjs-exporter-2.0.0 -> 2.1.2
wagtail-2.0.2 -> 2.2.2

And now it works! (with wagtail 2.2.2) 
:)

So, I think is just about to update setup file... but I'm not sure
What do you think?

**Comment by filippovd20** [comment]
I'm experiencing exactly the same issue when using puput as a standalone app. Should I switch over to "installation on top of Wagtail"?

**Comment by ritterasdf** [comment]
For me, the issue only appears when "PUPUT_AS_PLUGIN" is set to False in base.py. I also managed to change wagtails search function in a way that gets rid of the circular dependency but it's not a nice solution at all.

**Comment by ritterasdf** [comment]
I'm pretty sure the issue with Wagtail 2.2 comes from the puput/urls.py section on 'PUPUT_AS_PLUGIN'. If blog_admin and search are commented out, puput runs fine. If those two sections are left in, the issue mentioned above appears because puput is trying to add urlpatterns which are added by Wagtail itself already.

**Comment by MiltonLn** [comment]
Is anybody working yet on upgrading `puput` to be compatible with `Wagtail 2.2.x`?

**Comment by marctc** [comment]
Not me. I'm too busy to work on it right now. Do you want to try it @MiltonLn?

**Comment by sathishscripts** [comment]
wagtail 2.3 is released. So it would be better to migrate to this version.

**Comment by MiltonLn** [comment]
Take a look at #179, once that is merged we can close this PR
