### ISSUE TITLE
URL issues with install over existing wagtail instance

### ISSUE THREAD

**Issue by nstephenh** [APSL/puput#231]
Hello
I'm trying to install puput over my existing wagtail instance. I've set puput to be a plugin in my settings, but I'm still running into the following error. Any help debugging would be appreciated. Thanks!

`[04/Oct/2020 22:58:08] "GET /cms/pages/7/view_draft/ HTTP/1.1" 500 175682
Internal Server Error: /
Traceback (most recent call last):
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/wagtail/core/models.py", line 1592, in _get_response
    response = response.render()
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/template_profiler_panel/panels/template.py", line 55, in render_wrapper
    result = wrapped(*args, **kwargs)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/puput/templatetags/puput_tags.py", line 77, in canonical_url
    return context.request.build_absolute_uri(entry_url(context, entry, entry.blog_page))
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/puput/templatetags/puput_tags.py", line 71, in entry_url
    return get_entry_url(entry, blog_page.page_ptr, Site.find_for_request(context['request']).root_page)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/puput/urls.py", line 81, in get_entry_url
    blog_path = strip_prefix_and_ending_slash(blog_page.specific.last_url_part)
  File "/media/nsh/LinuxHDD/CGT/Code/shopcgt/venv/lib/python3.8/site-packages/puput/utils.py", line 31, in strip_prefix_and_ending_slash
    return path.replace(reverse('wagtail_serve', args=[""]), '', 1).rstrip("/")
AttributeError: 'NoneType' object has no attribute 'replace'
[04/Oct/2020 23:01:48] "GET /cms/pages/7/view_draft/ HTTP/1.1" 500 175682
`

**Comment by bashu** [comment]
I can't read this, feel free to re-open this issue, if it was not fixed
