### ISSUE TITLE
Circular Import Error with 'include('puput.urls')' in Django urls.py

### ISSUE THREAD

**Issue by thedern** [APSL/puput#239]
Per the puput documentation for configuring a standalone blog app, when adding 'path(' ', include('puput.urls'))', to my urls.py,  I receive a circlar import error when get_entry_url and get_feeds_url are imported .  See below.

Note:  I am attempting to add Puput to a django **3.14** installation.

Traceback (most recent call last):
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  **File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/puput/templatetags/puput_tags.py", line 10, in <module>
    from ..urls import get_entry_url, get_feeds_url**
ImportError: cannot import name 'get_entry_url' from partially initialized module 'puput.urls' (most likely due to a circular import) (/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/puput/urls.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/thedern/code/python/django/test/djangox/config/urls.py", line 10, in <module>
    path('blog/', include('puput.urls')),
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/puput/urls.py", line 39, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 104, in <module>
    path(f"sprite-{get_sprite_hash()}/", home.sprite, name="wagtailadmin_sprite"),
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 95, in get_sprite_hash
    content = str(home.sprite(None).content, "utf-8")
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/wagtail/admin/views/home.py", line 224, in sprite
    return HttpResponse(icons())
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/wagtail/admin/views/home.py", line 219, in icons
    _icons_html = render_to_string("wagtailadmin/shared/icons.html", {'icons': all_icons})
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 123, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'puput.templatetags.puput_tags': cannot import name 'get_entry_url' from partially initialized module 'puput.urls' (most likely due to a circular import) (/home/thedern/code/python/django/test/djangox/venv/lib/python3.8/site-packages/puput/urls.py)

**Comment by m1sraapurva** [comment]
For me, this error occurred when I used the instructions in [Standalone blog app](https://puput.readthedocs.io/en/latest/setup.html#standalone-blog-app) , setting up the urls.py as :
```python 
urlpatterns = [
    ...
    path(r'', include('puput.urls')),
]
```

However, when I tried the [Installation on top of Wagtail](https://puput.readthedocs.io/en/latest/setup.html#installation-on-top-of-wagtail) section, the urls where included like this:
```python
 from puput import urls as puput_urls
 urlpatterns = [
    ...
    url(r'',include(puput_urls)),
    ...
]
```
Above worked fine.

**Comment by lanshark** [comment]
This is also happening for me with a standard checkout of current master, when running tox.  ALL tests failed with the same error.

ERROR:   py36-dj20: commands failed
ERROR:   py36-dj21: commands failed
ERROR:   py36-dj22: commands failed
ERROR:   py36-dj30: commands failed
ERROR:   py37-dj20: commands failed
ERROR:   py37-dj21: commands failed
ERROR:   py37-dj22: commands failed
ERROR:   py37-dj30: commands failed
ERROR:   py38-dj20: commands failed
ERROR:   py38-dj21: commands failed
ERROR:   py38-dj22: commands failed
ERROR:   py38-dj30: commands failed
  flake8: commands succeeded

**Comment by Pei2tech** [comment]
I also got these errors as configuring the standalone blog and running the command `python manage.py runserver` However, there is no issue as using wsgi server `gunicorn xxx.wsgi `

**Comment by bashu** [comment]
still not fixed

**Comment by bashu** [comment]
works just fine with `wagtail==2.8.2` and `django==3.0.14`

**Comment by bashu** [comment]
to @thedern and @ckz8780 can you checkout `develop` branch and let me know if it was fixed or not

**Comment by ckz8780** [comment]
@bashu Thanks for the reply and sorry for the delay in response! It does seem to work. I've installed v1.1.2, wagtail 2.15 and Django 3.2.9. I'm working on a bunch of other upgrades so I won't know for sure if this combo will work together for a bit but the changes definitely fixed the circular import issue. Thank you!
