### ISSUE TITLE
puput, django-el-pagination and django 1.10.x

### ISSUE THREAD

**Issue by bashu** [APSL/puput#73]
I got this 
```
Traceback (most recent call last):
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/defaulttags.py", line 510, in render
    return self.nodelist.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/el_pagination/templatetags/el_pagination_tags.py", line 311, in render
    page = paginator.page(page_number)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/el_pagination/paginators.py", line 58, in page
    number = self.validate_number(number)
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/django/core/paginator.py", line 39, in validate_number
    if number > self.num_pages:
  File "/Users/bashu/.virtualenvs/metadata/lib/python2.7/site-packages/el_pagination/paginators.py", line 69, in _get_num_pages
    if self._num_pages is None:
AttributeError: 'DefaultPaginator' object has no attribute '_num_pages'
```

**Comment by bashu** [comment]
never mind looks like already fixed in master
