### ISSUE TITLE
PUPUT_ENTRY_MODEL=... 

### ISSUE THREAD

**Issue by bashu** [APSL/puput#9]
```python
...
PUPUT_ENTRY_MODEL = 'blogger.EntryAbstract'
...
```

gave me this:
```python
/home/vagrant/.virtualenv/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

Traceback (most recent call last):
  File "/home/vagrant/.virtualenv/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/vagrant/.virtualenv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/puput/models.py", line 24, in <module>
    Entry = import_model(getattr(settings, 'PUPUT_ENTRY_MODEL', EntryAbstract))
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/puput/utils.py", line 13, in import_model
    return getattr(import_module(package), attr)
AttributeError: 'module' object has no attribute 'EntryAbstract'
```
however 
```shell
[bodytherapy djangoapp]$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blogger import EntryAbstract
>>>
```

**Comment by marctc** [comment]
Where do you have defined your `EntryAbstract` class? In blogger.py? The only strange thing that I can see is that you are defining this:
```python
PUPUT_ENTRY_MODEL = 'blogger.EntryAbstract'
```
instead of 
```python
PUPUT_ENTRY_MODEL = 'blogger.models.EntryAbstract'
```
Is this correct?

**Comment by bashu** [comment]
nevermind, I've messed elsewhere...

**Comment by marctc** [comment]
NP @bashu. Do you think that the documentation is confusing on this topic?
